<template>
  <div class="page routes-page">
    <PageHeader title="升级路线" subtitle="把替换、升级和淘汰计划放在同一条时间线上。"><PrimaryButton label="新建路线" :icon="plusIcon" @click="openRoute()" /></PageHeader>
    <AsyncState :loading="loading" :error="error" :empty="routes.length===0" empty-title="还没有升级路线" empty-text="建立一条路线，把下一次升级拆成清晰的预算节点。" @retry="loadRoutes"><template #empty-action><PrimaryButton label="新建路线" :icon="plusIcon" @click="openRoute()" /></template>
      <section v-if="currentRoute" class="dark-card summary-banner"><div class="lead"><span>年度升级预算</span><strong>{{money(currentRoute.annualBudget)}}</strong></div><p>已规划 {{money(plannedBudget)}}</p><p class="lime">预计回收 {{money(expectedRecovery)}}</p><p>净投入 {{money(plannedBudget-expectedRecovery)}}</p><div class="route-progress"><div class="progress-track"><div class="progress-fill" :style="progressStyle(budgetRate)"></div></div><span>{{budgetRate}}%</span></div></section>
      <section class="route-switcher"><el-select v-model="selectedRouteId" class="dl-select" @change="loadGraph"><el-option v-for="r in routes" :key="r.id" :label="routeLabel(r)" :value="r.id" /></el-select><div class="list-actions"><button class="text-button" @click="openRoute(currentRoute)">编辑路线</button><button class="text-button" @click="nodeDialog=true">添加节点</button><button class="text-button" :disabled="!canLink" @click="linkDialog=true">添加连线</button><button class="text-button danger" @click="removeRoute">删除路线</button></div></section>
      <AsyncState :loading="graphLoading" :error="graphError" :empty="!graph?.nodes.length" empty-title="路线里还没有节点" empty-text="添加第一个升级节点，规划预算和回收金额。" @retry="loadGraph"><template #empty-action><PrimaryButton label="添加节点" :icon="plusIcon" @click="nodeDialog=true" /></template>
        <section v-if="graph" class="timeline"><article v-for="node in orderedNodes" :key="node.nodeId" class="timeline-row"><div class="period">{{node.periodLabel||'待定'}}</div><div class="timeline-mark" :class="{ready:node.status==='READY'||node.status==='COMPLETED'}"><span /></div><div class="card route-node"><div><h3>{{node.title||node.label||node.name||'升级节点'}}</h3><p><span v-if="node.name">{{node.name}}</span><template v-if="node.targetName"><b>升级到</b>{{node.targetName}}</template></p></div><div class="node-budget"><strong>预算 {{money(node.plannedBudget||node.purchasePrice)}}</strong><span>预计回收 {{money(node.expectedRecovery||node.salePrice)}}</span></div><span class="tag" :class="{lime:node.status==='READY'||node.status==='COMPLETED'}">{{statusLabel(node.status)}}</span><div class="node-actions"><button class="text-button" @click="openNode(node)">编辑</button><button class="text-button danger" @click="removeNode(node.nodeId)">删除</button></div></div></article></section>
      </AsyncState>
    </AsyncState>

    <el-dialog v-model="routeDialog" :title="editingRoute?'编辑路线':'新建路线'" width="600px"><el-form label-position="top" class="dialog-form"><div class="dialog-grid"><el-form-item label="路线名称" required><el-input v-model="routeForm.name"/></el-form-item><el-form-item label="计划年份"><el-input-number v-model="routeForm.planYear" :min="2020" :max="2100"/></el-form-item><el-form-item label="年度预算"><el-input-number v-model="routeForm.annualBudget" :min="0" :precision="2"/></el-form-item><el-form-item label="起点物品 ID"><el-input-number v-model="routeForm.rootAssetId" :min="1"/></el-form-item></div><el-form-item label="路线说明"><el-input v-model="routeForm.remark" type="textarea"/></el-form-item></el-form><template #footer><button class="secondary-button" @click="routeDialog=false">取消</button><PrimaryButton label="保存路线" :loading="saving" @click="saveRoute"/></template></el-dialog>
    <el-dialog v-model="nodeDialog" :title="editingNodeId?'编辑节点':'添加节点'" width="640px"><el-form label-position="top" class="dialog-form"><div class="dialog-grid"><el-form-item label="节点标题" required><el-input v-model="nodeForm.title"/></el-form-item><el-form-item label="阶段"><el-input v-model="nodeForm.periodLabel" placeholder="例如 Q3"/></el-form-item><el-form-item label="关联物品 ID"><el-input-number v-model="nodeForm.assetId" :min="1"/></el-form-item><el-form-item label="目标物品"><el-input v-model="nodeForm.targetName"/></el-form-item><el-form-item label="计划预算"><el-input-number v-model="nodeForm.plannedBudget" :min="0" :precision="2"/></el-form-item><el-form-item label="预计回收"><el-input-number v-model="nodeForm.expectedRecovery" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-select v-model="nodeForm.status"><el-option v-for="s in nodeStatuses" :key="s" :label="statusLabel(s)" :value="s"/></el-select></el-form-item></div><el-form-item label="说明"><el-input v-model="nodeForm.remark" type="textarea"/></el-form-item></el-form><template #footer><button class="secondary-button" @click="nodeDialog=false">取消</button><PrimaryButton label="保存节点" :loading="saving" @click="saveNode"/></template></el-dialog>
    <el-dialog v-model="linkDialog" title="添加节点连线" width="500px"><el-form label-position="top" class="dialog-form"><el-form-item label="起点"><el-select v-model="linkForm.fromNodeId"><el-option v-for="n in graph?.nodes" :key="n.nodeId" :label="n.title||n.name||String(n.nodeId)" :value="n.nodeId"/></el-select></el-form-item><el-form-item label="终点"><el-select v-model="linkForm.toNodeId"><el-option v-for="n in graph?.nodes" :key="n.nodeId" :label="n.title||n.name||String(n.nodeId)" :value="n.nodeId"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model="linkForm.remark"/></el-form-item></el-form><template #footer><button class="secondary-button" @click="linkDialog=false">取消</button><PrimaryButton label="创建连线" :loading="saving" @click="saveLink"/></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'; import { ElMessage,ElMessageBox } from 'element-plus'; import { createRoute,createRouteLink,createRouteNode,deleteRoute,deleteRouteNode,fetchRouteGraph,fetchRoutes,updateRoute,updateRouteNode,type NodePayload,type RoutePayload } from '@/api/upgrade'; import type { UpgradeGraphNode,UpgradeNodeStatus,UpgradeRouteGraph,UpgradeRouteItem } from '@/types'
import PageHeader from '@/components/PageHeader.vue'; import PrimaryButton from '@/components/PrimaryButton.vue'; import AsyncState from '@/components/AsyncState.vue'; import plusIcon from '@/assets/icons/plus.svg'
const routes=ref<UpgradeRouteItem[]>([]),selectedRouteId=ref<number>(),graph=ref<UpgradeRouteGraph>(),loading=ref(true),error=ref(''),graphLoading=ref(false),graphError=ref(''),saving=ref(false),routeDialog=ref(false),nodeDialog=ref(false),linkDialog=ref(false),editingRoute=ref<UpgradeRouteItem>(),editingNodeId=ref<number>(); const nodeStatuses:UpgradeNodeStatus[]=['PLANNED','READY','EXECUTING','COMPLETED','CANCELLED']; const routeForm=reactive<RoutePayload>({name:'',planYear:new Date().getFullYear(),annualBudget:0}); const nodeForm=reactive<NodePayload>({title:'',status:'PLANNED',plannedBudget:0,expectedRecovery:0}); const linkForm=reactive({fromNodeId:undefined as unknown as number,toNodeId:undefined as unknown as number,remark:''})
// Graph totals intentionally prefer node-level contract fields and fall back to route aggregates for legacy responses.
const currentRoute=computed(()=>routes.value.find(v=>v.id===selectedRouteId.value)); const orderedNodes=computed(()=>[...(graph.value?.nodes||[])].sort((a,b)=>(a.sort||0)-(b.sort||0))); const plannedBudget=computed(()=>graph.value?.nodes.reduce((n,v)=>n+Number(v.plannedBudget||v.purchasePrice||0),0)||Number(currentRoute.value?.plannedBudget||0)); const expectedRecovery=computed(()=>graph.value?.nodes.reduce((n,v)=>n+Number(v.expectedRecovery||v.salePrice||0),0)||Number(currentRoute.value?.expectedRecovery||0)); const budgetRate=computed(()=>Math.min(100,Math.round(plannedBudget.value/Math.max(1,Number(currentRoute.value?.annualBudget||0))*100)))
const canLink=computed(()=>(graph.value?.nodes.length||0)>=2); const routeLabel=(r:UpgradeRouteItem)=>r.name.includes(String(r.planYear||''))?r.name:`${r.planYear||''} ${r.name}`.trim(); const progressStyle=(value:number)=>({width:`${value}%`})
const money=(n?:number)=>`¥ ${Number(n||0).toLocaleString('zh-CN')}`; const statusLabel=(s:string)=>({PLANNED:'计划中',READY:'准备执行',EXECUTING:'执行中',COMPLETED:'已完成',CANCELLED:'已取消','使用中':'使用中','已出售':'已完成'}[s]||s)
async function loadRoutes(){loading.value=true;error.value='';try{routes.value=await fetchRoutes();if(!selectedRouteId.value&&routes.value.length)selectedRouteId.value=routes.value[0].id;if(selectedRouteId.value)await loadGraph()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function loadGraph(){if(!selectedRouteId.value)return;graphLoading.value=true;graphError.value='';try{graph.value=await fetchRouteGraph(selectedRouteId.value)}catch(e){graphError.value=(e as Error).message}finally{graphLoading.value=false}}
function openRoute(item?:UpgradeRouteItem){editingRoute.value=item;Object.assign(routeForm,{name:'',planYear:new Date().getFullYear(),annualBudget:0,rootAssetId:undefined,remark:''},item||{});routeDialog.value=true}
function openNode(node?:UpgradeGraphNode){editingNodeId.value=node?.nodeId;Object.assign(nodeForm,{title:'',status:'PLANNED',plannedBudget:0,expectedRecovery:0,assetId:undefined,targetName:'',periodLabel:'',remark:''},node||{});nodeDialog.value=true}
async function run(task:()=>Promise<unknown>,after:()=>void,reloadGraph=false){saving.value=true;try{await task();ElMessage.success('操作已保存');after();if(reloadGraph)await loadGraph();else await loadRoutes()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
const saveRoute=()=>{if(!routeForm.name.trim()){ElMessage.warning('请输入路线名称');return}run(()=>editingRoute.value?updateRoute(editingRoute.value.id,routeForm):createRoute(routeForm),()=>routeDialog.value=false)}
const saveNode=()=>{if(!selectedRouteId.value||!nodeForm.title.trim()){ElMessage.warning('请输入节点标题');return}run(()=>editingNodeId.value?updateRouteNode(selectedRouteId.value!,editingNodeId.value,nodeForm):createRouteNode(selectedRouteId.value!,nodeForm),()=>{nodeDialog.value=false;editingNodeId.value=undefined},true)}
const saveLink=()=>{if(!selectedRouteId.value||!linkForm.fromNodeId||!linkForm.toNodeId||linkForm.fromNodeId===linkForm.toNodeId){ElMessage.warning('请选择两个不同节点');return}run(()=>createRouteLink(selectedRouteId.value!,linkForm),()=>linkDialog.value=false,true)}
async function removeRoute(){if(!selectedRouteId.value)return;try{await ElMessageBox.confirm('删除路线会同时移除其节点与连线，是否继续？','删除路线',{type:'warning'});await run(()=>deleteRoute(selectedRouteId.value!),()=>{selectedRouteId.value=undefined;graph.value=undefined})}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
async function removeNode(id:number){try{await ElMessageBox.confirm('确认删除这个升级节点？','删除节点',{type:'warning'});await run(()=>deleteRouteNode(selectedRouteId.value!,id),()=>undefined,true)}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
watch(nodeDialog,v=>{if(!v)editingNodeId.value=undefined});onMounted(loadRoutes)
</script>

<style scoped>
.route-switcher{height:78px;display:flex;align-items:center;justify-content:space-between}.route-switcher .dl-select{width:280px}.route-progress{width:140px;margin-left:auto}.route-progress>span{margin-top:7px;text-align:center}.timeline{position:relative;padding-bottom:24px}.timeline::before{content:'';position:absolute;top:20px;bottom:20px;left:61px;width:6px;border-radius:999px;background:var(--dl-bg-alt)}.timeline-row{position:relative;min-height:140px;display:grid;grid-template-columns:40px 42px 1fr;gap:14px}.period{padding-top:35px;color:var(--dl-text-secondary);font-size:11px;font-weight:700}.timeline-mark{z-index:1;width:38px;height:38px;margin-top:24px;display:grid;place-items:center;border:8px solid var(--dl-bg-alt);border-radius:50%;background:#fff}.timeline-mark.ready{border-color:var(--dl-lime)}.timeline-mark span{width:8px;height:8px;border-radius:50%;background:var(--dl-text)}.route-node{height:112px;padding:18px 22px;display:grid;grid-template-columns:1fr 190px 120px 95px;gap:14px;align-items:center}.route-node h3{margin:0;font-size:16px}.route-node p{display:flex;gap:12px;margin:10px 0 0;color:var(--dl-text-secondary);font-size:13px}.route-node p b{color:var(--dl-muted);font-size:10px;text-transform:uppercase}.node-budget{display:flex;flex-direction:column;gap:7px}.node-budget strong{font-size:14px}.node-budget span{color:var(--dl-text-secondary);font-size:11px}.node-actions{display:flex}
</style>
