<template>
  <div class="page wishlist-page">
    <PageHeader title="心愿单" subtitle="管理购买意向、预算和价格观察。"><PrimaryButton label="添加心愿" :icon="plusIcon" @click="openEditor()" /></PageHeader>
    <AsyncState :loading="loading" :error="error" :empty="items.length===0" empty-title="还没有购买计划" empty-text="记录目标价和优先级，等待合适的购买时机。" @retry="load"><template #empty-action><PrimaryButton label="添加心愿" :icon="plusIcon" @click="openEditor()" /></template>
      <section class="dark-card summary-banner"><div class="lead"><span>计划预算</span><strong>{{ money(totalBudget) }}</strong></div><p>已规划 {{ items.length }} 件物品</p><p class="lime">其中 {{ highPriority }} 件高优先级</p><div class="budget-progress"><span>目标价覆盖率 {{ priceCoverage }}%</span><div class="progress-track"><div class="progress-fill" :style="progressStyle(priceCoverage)"></div></div></div></section>
      <div class="wishlist-heading"><h2>优先购买</h2><span>按优先级排列</span></div>
      <section class="wish-grid"><article v-for="(item,index) in sortedItems" :key="item.id" class="card wish-card"><div class="wish-visual" :class="{soft:index%2}"><img v-if="item.imageUrl" :src="item.imageUrl" :alt="item.name"/><strong v-else>{{ initials(item.name) }}</strong></div><div class="wish-copy"><h3>{{ item.name }}</h3><span class="tag" :class="{lime:(item.priority||0)>=3}">{{ priorityLabel(item.priority) }}</span><small>目标价</small><b>{{ money(item.expectedPrice) }}</b><p v-if="item.currentPrice">当前 {{ money(item.currentPrice) }} <em :class="{up:(item.priceChangeRate||0)>0}">{{ rate(item.priceChangeRate) }}</em></p><div class="wish-actions"><button class="text-button" @click="openEditor(item)">编辑</button><el-dropdown trigger="click"><button class="text-button">更多操作</button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="openPrice(item)">更新价格</el-dropdown-item><el-dropdown-item @click="openHistory(item)">价格历史</el-dropdown-item><el-dropdown-item @click="markPurchased(item)">标记已购买</el-dropdown-item><el-dropdown-item @click="openConvert(item)">转为物品</el-dropdown-item><el-dropdown-item divided @click="remove(item)">删除心愿</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></div></article></section>
      <section class="card price-table"><h2>价格观察</h2><div class="price-row table-head"><span>物品</span><span>当前价</span><span>目标价</span><span>变化</span><span>建议</span></div><div v-for="item in items" :key="item.id" class="price-row"><strong>{{item.name}}</strong><span>{{money(item.currentPrice)}}</span><b>{{money(item.expectedPrice)}}</b><em :class="{up:(item.priceChangeRate||0)>0}">{{rate(item.priceChangeRate)}}</em><span>{{suggestion(item)}}</span></div></section>
    </AsyncState>

    <el-dialog v-model="editorOpen" :title="editing ? '编辑心愿' : '添加心愿'" width="620px"><el-form label-position="top" class="dialog-form"><div class="dialog-grid"><el-form-item label="名称" required><el-input v-model="wishForm.name" /></el-form-item><el-form-item label="目标价"><el-input-number v-model="wishForm.expectedPrice" :min="0" :precision="2" /></el-form-item><el-form-item label="优先级"><el-select v-model="wishForm.priority"><el-option label="高优先级" :value="3"/><el-option label="中优先级" :value="2"/><el-option label="低优先级" :value="1"/></el-select></el-form-item><el-form-item label="分类"><QuickCategorySelect v-model="wishForm.categoryId" :categories="categories" @created="addCategory" /></el-form-item></div><el-form-item label="商品链接"><el-input v-model="wishForm.link" /></el-form-item><el-form-item label="备注"><el-input v-model="wishForm.notes" type="textarea" /></el-form-item></el-form><template #footer><button class="secondary-button" @click="editorOpen=false">取消</button><PrimaryButton label="保存心愿" :loading="saving" @click="saveWish" /></template></el-dialog>
    <el-dialog v-model="priceOpen" title="记录当前价格" width="430px"><el-form label-position="top" class="dialog-form"><el-form-item label="当前价格"><el-input-number v-model="currentPrice" :min="0" :precision="2" /></el-form-item></el-form><template #footer><button class="secondary-button" @click="priceOpen=false">取消</button><PrimaryButton label="保存价格" :loading="saving" @click="savePrice" /></template></el-dialog>
    <el-dialog v-model="historyOpen" title="价格历史" width="560px"><div v-if="historyLoading" class="small-loading">正在加载…</div><div v-else-if="history.length" class="history-list"><div v-for="point in history" :key="point.capturedAt"><strong>{{money(point.price)}}</strong><time>{{formatTime(point.capturedAt)}}</time></div></div><div v-else class="small-loading">暂无价格记录</div></el-dialog>
    <el-dialog v-model="convertOpen" title="转为物品" width="620px"><el-form label-position="top" class="dialog-form"><div class="dialog-grid"><el-form-item label="物品名称" required><el-input v-model="convertForm.name" /></el-form-item><el-form-item label="分类" required><QuickCategorySelect v-model="convertForm.categoryId" :categories="categories" @created="addCategory" /></el-form-item><el-form-item label="状态"><el-select v-model="convertForm.status"><el-option label="使用中" value="使用中"/><el-option label="已闲置" value="已闲置"/></el-select></el-form-item><el-form-item label="购买日期"><el-date-picker v-model="convertForm.purchaseDate" value-format="YYYY-MM-DD" placeholder="请选择购买日期" :shortcuts="dateShortcuts" /></el-form-item></div></el-form><template #footer><button class="secondary-button" @click="convertOpen=false">取消</button><PrimaryButton label="创建物品" :loading="saving" @click="saveConvert" /></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage,ElMessageBox } from 'element-plus'
import { createWishlist,deleteWishlist,fetchPriceHistory,fetchWishlist,markWishlistPurchased,updateWishlist,updateWishlistPrice,convertWishlist } from '@/api/wishlist'; import { fetchCategories } from '@/api/settings'; import type { AssetPayload,CategoryNode,PricePoint,WishlistItem,WishlistPayload } from '@/types'
import PageHeader from '@/components/PageHeader.vue'; import PrimaryButton from '@/components/PrimaryButton.vue'; import AsyncState from '@/components/AsyncState.vue'; import QuickCategorySelect from '@/components/QuickCategorySelect.vue'; import plusIcon from '@/assets/icons/plus.svg'
const router=useRouter(); const items=ref<WishlistItem[]>([]),categories=ref<CategoryNode[]>([]),loading=ref(true),error=ref(''),saving=ref(false),editorOpen=ref(false),priceOpen=ref(false),historyOpen=ref(false),convertOpen=ref(false),historyLoading=ref(false),editing=ref<WishlistItem>(),selected=ref<WishlistItem>(),currentPrice=ref(0),history=ref<PricePoint[]>([])
const wishForm=reactive<WishlistPayload>({name:'',priority:2}); const convertForm=reactive<AssetPayload>({name:'',categoryId:undefined as unknown as number,status:'使用中',purchases:[]})
const dateShortcuts=[{text:'今天',value:()=>new Date()}]
// Budget and price signals are derived from the current DTO so older wishlist rows with null price fields remain valid.
const sortedItems=computed(()=>[...items.value].sort((a,b)=>(b.priority||0)-(a.priority||0))); const totalBudget=computed(()=>items.value.reduce((n,v)=>n+Number(v.expectedPrice||0),0)); const highPriority=computed(()=>items.value.filter(v=>(v.priority||0)>=3).length); const priceCoverage=computed(()=>items.value.length?Math.round(items.value.filter(v=>v.currentPrice!=null).length/items.value.length*100):0)
const money=(n?:number)=>n==null?'—':`¥ ${Number(n).toLocaleString('zh-CN')}`; const initials=(n:string)=>n.slice(0,2); const priorityLabel=(n=1)=>['低优先级','低优先级','中优先级','高优先级'][n]||'低优先级'; const rate=(n?:number)=>n==null?'—':`${n>0?'↑':'↓'} ${Math.abs(n).toFixed(1)}%`; const suggestion=(v:WishlistItem)=>!v.currentPrice?'等待价格':v.currentPrice<=(v.expectedPrice||0)?'可以购买':v.currentPrice/(v.expectedPrice||1)<1.08?'接近目标':'继续观察'; const formatTime=(v:string)=>new Date(v).toLocaleString('zh-CN')
const progressStyle=(value:number)=>({width:`${value}%`})
function insertCategory(nodes:CategoryNode[],category:CategoryNode):CategoryNode[]{if(!category.parentId)return[...nodes,category];return nodes.map(node=>node.id===category.parentId?{...node,children:[...(node.children||[]),category]}:{...node,children:insertCategory(node.children||[],category)})}
function addCategory(category:CategoryNode){categories.value=insertCategory(categories.value,category)}
async function load(){loading.value=true;error.value='';try{items.value=await fetchWishlist()}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function openEditor(item?:WishlistItem){editing.value=item;Object.assign(wishForm,{name:'',priority:2,expectedPrice:undefined,categoryId:undefined,link:'',notes:''},item||{});editorOpen.value=true}
async function run(task:()=>Promise<unknown>,close:()=>void){saving.value=true;try{await task();ElMessage.success('操作已保存');close();await load()}catch(e){ElMessage.error((e as Error).message)}finally{saving.value=false}}
const saveWish=()=>{if(!wishForm.name.trim()){ElMessage.warning('请输入名称');return}run(()=>editing.value?updateWishlist(editing.value.id,wishForm):createWishlist(wishForm),()=>editorOpen.value=false)}
function openPrice(item:WishlistItem){selected.value=item;currentPrice.value=item.currentPrice||0;priceOpen.value=true} const savePrice=()=>selected.value&&run(()=>updateWishlistPrice(selected.value!.id,currentPrice.value),()=>priceOpen.value=false)
async function openHistory(item:WishlistItem){selected.value=item;historyOpen.value=true;historyLoading.value=true;try{history.value=await fetchPriceHistory(item.id)}catch(e){ElMessage.error((e as Error).message)}finally{historyLoading.value=false}}
const markPurchased=(item:WishlistItem)=>run(()=>markWishlistPurchased(item.id),()=>undefined)
async function remove(item:WishlistItem){try{await ElMessageBox.confirm(`确认删除“${item.name}”？`,'删除心愿',{type:'warning'});await run(()=>deleteWishlist(item.id),()=>undefined)}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error((e as Error).message)}}
function openConvert(item:WishlistItem){selected.value=item;Object.assign(convertForm,{name:item.name,categoryId:item.categoryId,status:'使用中',purchaseDate:new Date().toISOString().slice(0,10),coverImageUrl:item.imageUrl,notes:item.notes,purchases:[]});convertOpen.value=true}
const saveConvert=()=>{if(!selected.value||!convertForm.categoryId){ElMessage.warning('请选择物品分类');return}run(async()=>{const id=await convertWishlist(selected.value!.id,convertForm);convertOpen.value=false;await router.push(`/assets/${id}`)},()=>undefined)}
onMounted(()=>{fetchCategories().then(v=>categories.value=v).catch(()=>undefined);load()})
</script>

<style scoped>
.budget-progress{width:214px;margin-left:auto}.budget-progress span{margin-bottom:10px}.wishlist-heading{height:78px;display:flex;align-items:end;justify-content:space-between;padding-bottom:16px}.wishlist-heading h2{margin:0;font-size:18px}.wishlist-heading span{color:var(--dl-text-secondary);font-size:12px}.wish-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.wish-card{height:194px;padding:16px;display:grid;grid-template-columns:128px 1fr;gap:20px}.wish-visual{height:162px;display:grid;place-items:center;overflow:hidden;border-radius:var(--dl-radius-md);background:var(--dl-accent-soft)}.wish-visual.soft{background:var(--dl-bg-alt)}.wish-visual img{width:100%;height:100%;object-fit:cover}.wish-visual strong{font-size:26px}.wish-copy{min-width:0}.wish-copy h3{margin:3px 0 12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:16px}.wish-copy small{display:block;margin-top:14px;color:var(--dl-text-secondary);font-size:11px}.wish-copy>b{display:block;margin-top:5px;font-size:19px}.wish-copy p{height:15px;margin:1px 0;color:var(--dl-text-secondary);font-size:10px}.wish-copy em,.price-row em{color:var(--dl-success);font-style:normal;font-weight:600}.wish-copy em.up,.price-row em.up{color:var(--dl-warning)}.wish-actions{display:flex;margin-left:-6px}.price-table{margin-top:32px;padding:20px 22px}.price-table h2{margin:0 0 16px;font-size:17px}.price-row{display:grid;grid-template-columns:2fr repeat(4,1fr);align-items:center;min-height:56px;border-top:1px solid #eceee9;font-size:12px}.price-row.table-head{min-height:34px;border:0;color:var(--dl-text-secondary);font-size:11px}.history-list>div{height:52px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #eceee9}.history-list time{color:var(--dl-muted);font-size:12px}.small-loading{height:120px;display:grid;place-items:center;color:var(--dl-muted);font-size:12px}
</style>
